In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/dai-tut-2/Plastic Waste Around the World.csv


In [2]:
import pandas as pd

# Load the dataset
csv_file_path = '/kaggle/input/dai-tut-2/Plastic Waste Around the World.csv'  # Replace with the actual path to your CSV file
data = pd.read_csv(csv_file_path)

# Perform one-hot encoding on categorical columns: 'Country', 'Main_Sources', and 'Coastal_Waste_Risk'
encoded_data = pd.get_dummies(data, columns=['Country', 'Main_Sources', 'Coastal_Waste_Risk'], drop_first=True)

# Display the first few rows of the encoded dataset
print(encoded_data.head())

# If you want to save the encoded dataset to a new CSV file
encoded_data.to_csv('encoded_dataset.csv', index=False)


   Total_Plastic_Waste_MT  Recycling_Rate  Per_Capita_Waste_KG  \
0                   59.08            29.8                 41.2   
1                   42.02            32.1                127.5   
2                   26.33            11.5                 19.3   
3                    7.99            84.8                 63.2   
4                    6.28            56.1                 75.6   

   Country_Albania  Country_Algeria  Country_Angola  Country_Argentina  \
0            False            False           False              False   
1            False            False           False              False   
2            False            False           False              False   
3            False            False           False              False   
4            False            False           False              False   

   Country_Armenia  Country_Australia  Country_Austria  ...  \
0            False              False            False  ...   
1            False              

In [3]:
data.shape

(165, 6)

In [4]:
data.info

<bound method DataFrame.info of               Country  Total_Plastic_Waste_MT           Main_Sources  \
0               China                   59.08   Packaging_Industrial   
1       United States                   42.02     Packaging_Consumer   
2               India                   26.33         Consumer_Goods   
3               Japan                    7.99  Packaging_Electronics   
4             Germany                    6.28   Automotive_Packaging   
..                ...                     ...                    ...   
160  Marshall Islands                    0.01     Consumer_Packaging   
161        Micronesia                    0.01     Consumer_Packaging   
162             Palau                    0.01     Consumer_Packaging   
163            Tuvalu                    0.01     Consumer_Packaging   
164             Nauru                    0.01     Consumer_Packaging   

     Recycling_Rate  Per_Capita_Waste_KG Coastal_Waste_Risk  
0              29.8                 41.2 

In [5]:
data.describe

<bound method NDFrame.describe of               Country  Total_Plastic_Waste_MT           Main_Sources  \
0               China                   59.08   Packaging_Industrial   
1       United States                   42.02     Packaging_Consumer   
2               India                   26.33         Consumer_Goods   
3               Japan                    7.99  Packaging_Electronics   
4             Germany                    6.28   Automotive_Packaging   
..                ...                     ...                    ...   
160  Marshall Islands                    0.01     Consumer_Packaging   
161        Micronesia                    0.01     Consumer_Packaging   
162             Palau                    0.01     Consumer_Packaging   
163            Tuvalu                    0.01     Consumer_Packaging   
164             Nauru                    0.01     Consumer_Packaging   

     Recycling_Rate  Per_Capita_Waste_KG Coastal_Waste_Risk  
0              29.8                 41.

In [6]:
data.isnull().sum()

Country                   0
Total_Plastic_Waste_MT    0
Main_Sources              0
Recycling_Rate            0
Per_Capita_Waste_KG       0
Coastal_Waste_Risk        0
dtype: int64

In [7]:
# Assuming 'Recycling_Rate' is the target variable
target_column = 'Recycling_Rate'

# Separating features (X) and target (y)
X = encoded_data.drop(columns=[target_column])  # Features: all columns except the target
y = encoded_data[target_column]  # Target: the column we want to predict

# Display the shape of X (features) and y (target)
print(f'Features (X) shape: {X.shape}')
print(f'Target (y) shape: {y.shape}')


Features (X) shape: (165, 178)
Target (y) shape: (165,)


In [8]:
# Convert 'yes'/'no' values in the target column to binary (1 for 'yes', 0 for 'no')
y_binary = y.map({'yes': 1, 'no': 0})

# Display the first few values of the binary target column
print(y_binary.head())


0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Recycling_Rate, dtype: float64


In [9]:
from sklearn.model_selection import train_test_split

# Split data into training and testing sets (80% train, 20% test by default)
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

# Display the shapes of the training and testing sets
print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')


X_train shape: (132, 178)
X_test shape: (33, 178)
y_train shape: (132,)
y_test shape: (33,)


In [10]:
import pandas as pd
from category_encoders import BinaryEncoder

# Example data
data = {'categorical_column': ['A', 'B', 'C', 'A', 'B', 'C']}
df = pd.DataFrame(data)

# Apply Binary Encoding
encoder = BinaryEncoder(cols=['categorical_column'])
df_encoded = encoder.fit_transform(df)

print(df_encoded)


   categorical_column_0  categorical_column_1
0                     0                     1
1                     1                     0
2                     1                     1
3                     0                     1
4                     1                     0
5                     1                     1


In [11]:
import pandas as pd
from category_encoders import BinaryEncoder

# Example data
data = {'categorical_column': ['A', 'B', 'C', 'A', 'B', 'C']}
df = pd.DataFrame(data)

# Apply Binary Encoding
encoder = BinaryEncoder(cols=['categorical_column'])
df_encoded = encoder.fit_transform(df)

# If you want to remove the extra column (e.g., the last column)
df_encoded = df_encoded.iloc[:, :-1]  # Removes the last column

print(df_encoded)


   categorical_column_0
0                     0
1                     1
2                     1
3                     0
4                     1
5                     1


In [12]:

import pandas as pd
from category_encoders import BinaryEncoder

# Sample dataset
data = {'categorical_column': ['A', 'B', 'C', 'A', 'B', 'C']}
df = pd.DataFrame(data)

# Apply Binary Encoding
encoder = BinaryEncoder(cols=['categorical_column'])
df_encoded = encoder.fit_transform(df)

# View the encoded data
print(df_encoded)
# Remove the last extra column if needed
df_encoded = df_encoded.iloc[:, :-1]


   categorical_column_0  categorical_column_1
0                     0                     1
1                     1                     0
2                     1                     1
3                     0                     1
4                     1                     0
5                     1                     1


In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Sample dataset
data = {'categorical_column': ['A', 'B', 'C', 'A', 'B', 'C']}
df = pd.DataFrame(data)

# Apply Label Encoding
label_encoder = LabelEncoder()
df['categorical_column_encoded'] = label_encoder.fit_transform(df['categorical_column'])

# View the encoded data
print(df)


  categorical_column  categorical_column_encoded
0                  A                           0
1                  B                           1
2                  C                           2
3                  A                           0
4                  B                           1
5                  C                           2


In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Sample dataset
data = {'categorical_column': ['A', 'B', 'C', 'A', 'B', 'C']}
df = pd.DataFrame(data)

# Apply Label Encoding
label_encoder = LabelEncoder()
df['categorical_column_encoded'] = label_encoder.fit_transform(df['categorical_column'])

# Drop the original categorical column
df = df.drop('categorical_column', axis=1)

# View the updated dataframe
print(df)


   categorical_column_encoded
0                           0
1                           1
2                           2
3                           0
4                           1
5                           2


In [15]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from category_encoders import OneHotEncoder, BinaryEncoder

# Sample dataset
data = {'categorical_column': ['A', 'B', 'C', 'A', 'B', 'C', 'D', 'E']}
df = pd.DataFrame(data)

# Count unique values
unique_values = df['categorical_column'].nunique()

# Set a threshold to decide between encoding methods
threshold = 10  # You can adjust this based on your use case

if unique_values <= threshold:
    # Use Label Encoding
    print(f"Using Label Encoding (Unique values: {unique_values})")
    label_encoder = LabelEncoder()
    df['categorical_column_encoded'] = label_encoder.fit_transform(df['categorical_column'])
else:
    # Use One-Hot or Binary Encoding (You can choose between these based on your preference)
    print(f"Using Binary Encoding (Unique values: {unique_values})")
    encoder = BinaryEncoder(cols=['categorical_column'])
    df = encoder.fit_transform(df)

# Drop the original column
df = df.drop('categorical_column', axis=1, errors='ignore')

# View the updated dataframe
print(df)


Using Label Encoding (Unique values: 5)
   categorical_column_encoded
0                           0
1                           1
2                           2
3                           0
4                           1
5                           2
6                           3
7                           4


In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load the dataset
data = pd.read_csv('/kaggle/input/dai-tut-2/Plastic Waste Around the World.csv')

# Encode categorical variables
label_encoder = LabelEncoder()

# Encode the target variable 'Coastal_Waste_Risk'
data['Coastal_Waste_Risk'] = label_encoder.fit_transform(data['Coastal_Waste_Risk'])

# Encode the 'Main_Sources' column as it contains categorical data
data['Main_Sources'] = label_encoder.fit_transform(data['Main_Sources'])

# Drop the 'Country' column since it's not a relevant feature for modeling
data = data.drop(columns=['Country'])

# Separate features (X) and target (y)
X = data.drop(columns=['Coastal_Waste_Risk'])
y = data['Coastal_Waste_Risk']

# Split the data into training and validation sets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)


In [17]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the SVM model with a linear kernel
svm_model = SVC(kernel='linear', random_state=42)

# Train the model on the training set
svm_model.fit(X_train, y_train)

# Make predictions on the validation set
y_pred = svm_model.predict(X_valid)

# Evaluate the model
accuracy = accuracy_score(y_valid, y_pred)
classification_rep = classification_report(y_valid, y_pred)
confusion_mat = confusion_matrix(y_valid, y_pred)

# Display results
print(f'Accuracy: {accuracy:.2f}')
print("\nClassification Report:")
print(classification_rep)
print("\nConfusion Matrix:")
print(confusion_mat)


Accuracy: 0.45

Classification Report:
              precision    recall  f1-score   support

           0       0.46      0.92      0.61        12
           1       0.44      0.36      0.40        11
           2       0.00      0.00      0.00         9
           3       0.00      0.00      0.00         1

    accuracy                           0.45        33
   macro avg       0.23      0.32      0.25        33
weighted avg       0.31      0.45      0.36        33


Confusion Matrix:
[[11  1  0  0]
 [ 7  4  0  0]
 [ 6  3  0  0]
 [ 0  1  0  0]]


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
